### ISSUE TITLE
NullReferenceException In LookupSymbols

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.InteractiveBrokers#101]
#### Expected Behavior
We can use IB Data Provider with other brokerages.

#### Actual Behavior
If we deploy an algorithm that  adds Futures with IB, we get the following exception:

```
2024-03-21T14:07:01.8531305Z ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 03/21/2024 14:06:59 UTC. Context: LiveSynchronizer System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage.LookupSymbols(Symbol symbol, Boolean includeExpired, String securityCurrency)
   at QuantConnect.Lean.Engine.DataFeeds.DataQueueHandlerManager.LookupSymbols(Symbol symbol, Boolean includeExpired, String securityCurrency) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Engine/DataFeeds/DataQueueHandlerManager.cs:line 176

```

#### Potential Solution
N/A

#### Reproducing the Problem
Deploy the following code to QC Paper and select IB as data provider.
```python
class RetrospectiveApricotLlama(QCAlgorithm):
    def Initialize(self):
        self.SetStartDate(2024, 3, 20)
        self.AddFuture("ES")
```

This issue was observed with Terminal Link with IB Data too.

#### System Information
QuantConnect Cloud.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Believe this issue has been fixed, can no longer reproduce `Deploy the following code to QC Paper and select IB as data provider.`
